name: Test Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print Info
      run: |
        echo "GitHub Actions is working!"
        echo "Current branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Repository: ${{ github.repository }}"